### PR TITLE
Update DataSetConverter4D.pas

### PR DESCRIPTION
**Pull request by JosepMariaGomez**
Update to add the dataset structure as 1st record of JSON conversion.

### CODE REVIEW

**Comment by JosepMariaGomez** [comment]
Please check for the availability to add this changes...
Is working fine, and is used because I use TClientDataset created in runtime, and I need to send the structure across a Web Service (don't care if REST or pure SOAP) as part of data.
Many Thanks.

**Comment by ezequieljuliano** [comment]
Very interesting, it is a useful feature.

Could you write a unit test to test all this?

Regards,
Ezequiel

**Comment by JosepMariaGomez** [comment]
Working on it... 
Also, I'm improving this new feature... 
It will be a little different... Please, may you cancel this pull? I'll create another...
I had some problems when JSON structure, has different struct objects (struct and data), and the struct will be sended in other request.

**Comment by ezequieljuliano** [comment]
Great. I will cancel yes all the pulls, once you have ready sent again that I will analyze.

**Comment by ezequieljuliano** [comment]
Will be reviewed and mailed again.

**Pull request closed without merging**
